# Generated by Django 6.0.5 on 2026-08-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despensa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='unidad_medida',
            field=models.CharField(choices=[('unidades', 'Unidades'), ('gramos', 'Gramos'), ('kilogramos', 'Kilogramos'), ('mililitros', 'Mililitros'), ('litros', 'Litros')], max_length=20),
        ),
    ]
