# Generated by Django 6.0.5 on 2026-08-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despensa', '0002_alter_alimento_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='unidad_medida',
            field=models.CharField(choices=[('gramos', 'Gramos'), ('kilogramos', 'Kilogramos'), ('mililitros', 'Mililitros'), ('litros', 'Litros'), ('unidades', 'Unidades')], max_length=20),
        ),
    ]
