name: Docker Build

on:
  push:
    tags:
      - "*"

jobs:
  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build .